name=DuinoClaw
version=1.0.0
author=ArtronShop Co., Ltd.
maintainer=Sonthaya Nongnuch <sonthaya.nt@hotmail.com>
sentence=Embed an AI agent into your Arduino projects with ease.
paragraph=DuinoClaw enables Arduino devices to integrate AI capabilities, including memory management and tool execution. It supports multiple AI providers, allowing developers to choose the most suitable backend for their applications.
category=Communication
url=https://github.com/ArtronShop/DuinoClaw
architectures=*
depends=ArduinoJson,UniversalTelegramBot
